"""Coverage for ``pyloxone_api.loxone_http_client`` (raise the 36% floor).

Pins three behaviours that had no test at all:

* ``LoxoneAsyncHttpClient._handle_error`` -- the full HTTP status -> exception
  map (every branch, including the Loxone-typed errors that must carry the
  originating ``response``) and the fallbacks used when the error body cannot
  be read.
* ``close()`` -- owned sessions are closed, borrowed ones are not, a second
  close is a warning-only no-op, and a failing close still marks the client
  closed.
* ``get()`` -- the aiohttp-exception translation table, the guard rails
  (closed client, empty endpoint, missing leading slash) and the UTF-8
  semantics of the Basic-auth header (JoDehli/PyLoxone#506).

Everything is faked: no socket is opened anywhere in this module.
"""

from __future__ import annotations

import base64
import logging
from types import SimpleNamespace

import aiohttp
import pytest

from custom_components.loxone.pyloxone_api.exceptions import (
    LoxoneMaxNumOfConnectionsError,
    LoxoneServiceUnAvailableError,
    LoxoneUnauthorisedError,
    LoxoneUnrecognizedCommandError,
)
from custom_components.loxone.pyloxone_api.loxone_http_client import (
    LoxoneAsyncHttpClient,
    _basic_auth_header,
)

_LOGGER_NAME = "custom_components.loxone.pyloxone_api.loxone_http_client"


def _response(status: int, *, body: bytes = b"boom", read_error: BaseException | None = None):
    """A minimal stand-in for an ``aiohttp`` response object."""

    async def _read() -> bytes:
        if read_error is not None:
            raise read_error
        return body

    return SimpleNamespace(status=status, content=SimpleNamespace(read=_read))


class _FakeSession:
    """Records ``get`` calls; raises ``error`` or returns ``response``."""

    def __init__(self, *, error: BaseException | None = None, response=None) -> None:
        self.closed = False
        self.calls: list[tuple[str, dict]] = []
        self.close_calls = 0
        self._error = error
        self._response = response

    async def get(self, url: str, **kwargs):
        self.calls.append((url, kwargs))
        if self._error is not None:
            raise self._error
        return self._response

    async def close(self) -> None:
        self.close_calls += 1
        self.closed = True


def _client(session: _FakeSession, *, scheme: str = "http", **kwargs) -> LoxoneAsyncHttpClient:
    return LoxoneAsyncHttpClient("ms.local:8080", "admin", "secret", scheme=scheme, session=session, **kwargs)


# --------------------------------------------------------------------------- #
# _handle_error: the status -> exception map
# --------------------------------------------------------------------------- #

# (status, exact exception type, exact message). Hand-transcribed from the
# spec, never generated by running the mapper.
_STATUS_MAP = [
    (400, ValueError, "Bad request to Loxone Miniserver: boom"),
    (401, LoxoneUnauthorisedError, "Unauthorized: boom"),
    (403, PermissionError, "Access forbidden: boom"),
    (404, LoxoneUnrecognizedCommandError, "Unrecognized command: boom"),
    (408, TimeoutError, "Request timeout: boom"),
    (429, RuntimeError, "Rate limit exceeded: boom"),
    (500, RuntimeError, "Miniserver internal error: boom"),
    (502, ConnectionError, "Bad gateway: boom"),
    (
        503,
        LoxoneServiceUnAvailableError,
        "Service Unavailable; The Miniserver is restarting and not ready for requests: boom",
    ),
    (504, TimeoutError, "Gateway timeout: boom"),
    (901, LoxoneMaxNumOfConnectionsError, "Maximum number of allowed concurrent connections reached: boom"),
    (418, RuntimeError, "HTTP error 418: boom"),
]


@pytest.mark.parametrize(("status", "expected_type", "expected_message"), _STATUS_MAP)
async def test_handle_error_maps_every_status(status, expected_type, expected_message) -> None:
    """Each documented status raises exactly its own type with its own text."""
    response = _response(status)

    with pytest.raises(expected_type) as excinfo:
        await LoxoneAsyncHttpClient._handle_error(response)

    # `is` and not `isinstance`: 429/500/418 all map to RuntimeError while
    # ConnectionError/TimeoutError are OSError subclasses, so a sloppy
    # isinstance check would let several branches masquerade as each other.
    assert type(excinfo.value) is expected_type
    assert str(excinfo.value) == expected_message


@pytest.mark.parametrize(
    ("status", "expected_type"),
    [
        (401, LoxoneUnauthorisedError),
        (404, LoxoneUnrecognizedCommandError),
        (503, LoxoneServiceUnAvailableError),
        (901, LoxoneMaxNumOfConnectionsError),
    ],
)
async def test_handle_error_attaches_response_to_loxone_errors(status, expected_type) -> None:
    """The Loxone-typed errors carry the originating response for the caller."""
    response = _response(status)

    with pytest.raises(expected_type) as excinfo:
        await LoxoneAsyncHttpClient._handle_error(response)

    assert excinfo.value.response is response


async def test_handle_error_decodes_body_with_replacement() -> None:
    """Undecodable bytes are replaced, not raised on (errors='replace')."""
    response = _response(400, body=b"caf\xe9")

    with pytest.raises(ValueError) as excinfo:
        await LoxoneAsyncHttpClient._handle_error(response)

    assert str(excinfo.value) == "Bad request to Loxone Miniserver: caf�"


@pytest.mark.parametrize(
    ("read_error", "expected_content"),
    [
        (TimeoutError("too slow"), "<timeout reading response>"),
        (UnicodeDecodeError("utf-8", b"\xff", 0, 1, "invalid start byte"), "<binary content>"),
        (OSError("socket gone"), "<error reading content: socket gone>"),
        (ValueError("bad chunk"), "<error reading content: bad chunk>"),
        (aiohttp.ClientPayloadError("payload gone"), "<error reading content: payload gone>"),
    ],
)
async def test_handle_error_body_read_failures(read_error, expected_content) -> None:
    """A body that cannot be read becomes a hand-written placeholder string."""
    response = _response(500, read_error=read_error)

    with pytest.raises(RuntimeError) as excinfo:
        await LoxoneAsyncHttpClient._handle_error(response)

    assert str(excinfo.value) == f"Miniserver internal error: {expected_content}"


# --------------------------------------------------------------------------- #
# close()
# --------------------------------------------------------------------------- #
async def test_close_closes_an_owned_session() -> None:
    """A session the client created itself is closed by close()."""
    client = LoxoneAsyncHttpClient("ms.local:8080", "admin", "secret")
    assert client._own_session is True
    session = client.session
    assert session.closed is False

    await client.close()

    assert session.closed is True
    assert client._closed is True


async def test_close_leaves_a_provided_session_open() -> None:
    """A borrowed session belongs to the caller: close() must not touch it."""
    session = _FakeSession()
    client = _client(session)
    assert client._own_session is False

    await client.close()

    assert session.close_calls == 0
    assert session.closed is False
    assert client._closed is True


async def test_second_close_only_warns(caplog) -> None:
    """Closing twice is a no-op that warns instead of raising."""
    session = _FakeSession()
    client = _client(session)
    await client.close()

    with caplog.at_level(logging.WARNING, logger=_LOGGER_NAME):
        await client.close()

    assert "HTTP client is already closed" in caplog.text


async def test_failing_close_raises_but_still_marks_closed() -> None:
    """A session whose close() blows up still leaves the client closed."""
    session = _FakeSession()
    client = _client(session)
    # Pretend the client owns the session so close() actually calls into it.
    client._own_session = True

    async def _explode() -> None:
        raise OSError("transport already torn down")

    session.close = _explode

    with pytest.raises(RuntimeError) as excinfo:
        await client.close()

    assert str(excinfo.value) == "Failed to close HTTP session: transport already torn down"
    assert client._closed is True


# --------------------------------------------------------------------------- #
# get(): guard rails
# --------------------------------------------------------------------------- #
async def test_get_on_closed_client_raises_runtime_error() -> None:
    """A closed client refuses further requests."""
    session = _FakeSession()
    client = _client(session)
    await client.close()

    with pytest.raises(RuntimeError) as excinfo:
        await client.get("/jdev/cfg/api")

    assert str(excinfo.value) == "HTTP client has been closed"
    assert session.calls == []


async def test_get_rejects_an_empty_endpoint() -> None:
    """An empty endpoint is a caller bug, not a request."""
    session = _FakeSession()
    client = _client(session)

    with pytest.raises(ValueError) as excinfo:
        await client.get("")

    assert str(excinfo.value) == "Endpoint cannot be empty"
    assert session.calls == []


async def test_get_prepends_missing_leading_slash_and_warns(caplog) -> None:
    """A slash-less endpoint is repaired (and reported) rather than mangled."""
    response = _response(200)
    session = _FakeSession(response=response)
    client = _client(session)

    with caplog.at_level(logging.WARNING, logger=_LOGGER_NAME):
        result = await client.get("jdev/cfg/api")

    assert result is response
    assert "Endpoint 'jdev/cfg/api' should start with '/'" in caplog.text
    url, kwargs = session.calls[0]
    assert url == "http://ms.local:8080/jdev/cfg/api"
    # Plain http never negotiates TLS, so no ssl kwarg is handed to aiohttp.
    assert "ssl" not in kwargs
    assert kwargs["headers"]["Authorization"] == "Basic " + base64.b64encode(b"admin:secret").decode("ascii")


async def test_get_passes_verify_ssl_for_https() -> None:
    """With scheme=https the verify_ssl flag reaches aiohttp as ssl=."""
    response = _response(200)
    session = _FakeSession(response=response)
    client = _client(session, scheme="https", verify_ssl=False)

    assert await client.get("/jdev/cfg/api") is response

    url, kwargs = session.calls[0]
    assert url == "https://ms.local:8080/jdev/cfg/api"
    assert kwargs["ssl"] is False


async def test_get_reraises_loxone_errors_unwrapped() -> None:
    """A 401 surfaces as LoxoneUnauthorisedError, not as a generic RuntimeError."""
    session = _FakeSession(response=_response(401))
    client = _client(session)

    with pytest.raises(LoxoneUnauthorisedError) as excinfo:
        await client.get("/jdev/cfg/api")

    assert str(excinfo.value) == "Unauthorized: boom"


# --------------------------------------------------------------------------- #
# get(): aiohttp exception translation
# --------------------------------------------------------------------------- #
_URL = "http://ms.local:8080/jdev/cfg/api"

_TRANSLATIONS = [
    (
        aiohttp.ClientConnectionError("no route"),
        ConnectionError,
        f"Failed to connect to Loxone Miniserver at {_URL}: no route",
    ),
    (TimeoutError("slow"), TimeoutError, f"Request to {_URL} timed out after 30 seconds"),
    (aiohttp.ClientPayloadError("payload gone"), ValueError, "Invalid response payload from server: payload gone"),
    (
        aiohttp.ClientResponseError(SimpleNamespace(real_url=_URL), (), status=500, message="kaput"),
        RuntimeError,
        f"HTTP response error: 500, message='kaput', url='{_URL}'",
    ),
    (aiohttp.ClientError("generic"), RuntimeError, "HTTP client error: generic"),
    (KeyError("surprise"), RuntimeError, "Unexpected error during HTTP request: 'surprise'"),
]


@pytest.mark.parametrize(("raised", "expected_type", "expected_message"), _TRANSLATIONS)
async def test_get_translates_transport_errors(raised, expected_type, expected_message) -> None:
    """Every aiohttp failure class becomes a stdlib exception with a stable text."""
    session = _FakeSession(error=raised)
    client = _client(session)

    with pytest.raises(expected_type) as excinfo:
        await client.get("/jdev/cfg/api")

    assert type(excinfo.value) is expected_type
    assert str(excinfo.value) == expected_message
    assert excinfo.value.__cause__ is raised


async def test_get_maps_server_disconnect_to_connection_error() -> None:
    """ServerDisconnectedError is claimed by the ClientConnectionError handler.

    It subclasses ClientConnectionError, so the *first* handler wins and the
    message is the generic connect one; the dedicated "Server disconnected
    unexpectedly" branch further down is unreachable.
    """
    raised = aiohttp.ServerDisconnectedError("bye")
    session = _FakeSession(error=raised)
    client = _client(session)

    with pytest.raises(ConnectionError) as excinfo:
        await client.get("/jdev/cfg/api")

    assert str(excinfo.value) == f"Failed to connect to Loxone Miniserver at {_URL}: bye"


# --------------------------------------------------------------------------- #
# __init__ validation + _basic_auth_header
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize(
    ("overrides", "message"),
    [
        ({"url": ""}, "URL cannot be empty"),
        ({"username": ""}, "Username cannot be empty"),
        ({"password": ""}, "Password cannot be empty"),
        ({"scheme": "ftp"}, "Invalid scheme 'ftp'. Must be 'http' or 'https'"),
        ({"verify_ssl": "yes"}, "verify_ssl must be a boolean"),
    ],
)
def test_init_validates_its_arguments(overrides, message) -> None:
    """Bad construction arguments fail loudly at __init__ time."""
    args = {"url": "ms.local:8080", "username": "admin", "password": "secret", "session": _FakeSession()}
    args.update(overrides)

    with pytest.raises(ValueError) as excinfo:
        LoxoneAsyncHttpClient(**args)

    assert str(excinfo.value) == message


def test_init_rejects_an_already_closed_session() -> None:
    """A dead borrowed session cannot be adopted."""
    session = _FakeSession()
    session.closed = True

    with pytest.raises(ValueError) as excinfo:
        _client(session)

    assert str(excinfo.value) == "Provided session is already closed"


def test_basic_auth_header_is_utf8() -> None:
    """Credentials are encoded UTF-8, not latin-1 (JoDehli/PyLoxone#506)."""
    # Hand-derived with the stdlib, independently of the module under test.
    expected = "Basic " + base64.b64encode("admin:pässwörd".encode()).decode("ascii")
    latin1 = "Basic " + base64.b64encode("admin:pässwörd".encode("latin-1")).decode("ascii")
    # Literal, not computed by the code under test.
    assert expected == "Basic YWRtaW46cMOkc3N3w7ZyZA=="
    assert expected != latin1

    assert _basic_auth_header("admin", "pässwörd") == expected


def test_basic_auth_header_fallback_without_aiohttp_helper(monkeypatch) -> None:
    """On aiohttp < 3.12 the header is built by hand -- with the same result."""
    monkeypatch.delattr(aiohttp, "encode_basic_auth", raising=False)

    assert _basic_auth_header("admin", "pässwörd") == "Basic YWRtaW46cMOkc3N3w7ZyZA=="
