"""WP-5.1: ``has_entity_name`` adoption and the entity-name snapshot.

Acceptance criteria (docs/review/2026-09-remediation-plan.md, WP-5.1):

  * the setup creates primary entities with an *empty* name attribute (the
    device name is the display name — no more "Living Room Light Living
    Room Light") and sub-entities with *short* names ("Override Reason",
    "Total");
  * a snapshot of the entity registry (domain, entity_id, unique_id, stored name,
    device name/model linkage) after a fixture setup matches
    ``tests/snapshots/entity_names.json`` — the diff of this file between
    the pre- and post-WP-5.1 runs is reviewed in the PR;
  * no "Device Device" duplication in the snapshot: no entity's stored
    name equals the name of its own device;
  * every loxone entry carries ``has_entity_name = True``;
  * the enum sensor's translation key resolves via the HA core file
    layout ``component.loxone.entity.sensor.override_reason.state.<slug>``.

The snapshot file is generated by re-running this test with
``LOXONE_ENTITY_SNAPSHOT_OUT=/path/to/out.json pytest -q tests/test_entity_name_snapshot.py``
and then reviewed by hand (every name is read from
``tests/fixtures/LoxAPP3.json`` or the Miniserver fixture identity).
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
from homeassistant.config_entries import ConfigEntryState
from homeassistant.helpers import device_registry as dr, entity_registry as er
from homeassistant.helpers.translation import recursive_flatten

from custom_components.loxone import DOMAIN
from custom_components.loxone.lights.dimmer import LoxoneDimmer
from custom_components.loxone.sensor import (
    LoxoneRoomControllerOverrideSensor,
    LoxoneSensor,
)
from custom_components.loxone.switch import (
    LoxoneLightPresenceSwitch,
    LoxoneRoomControllerOverride,
    LoxoneSwitch,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT_PATH = Path(__file__).resolve().parent / "snapshots" / "entity_names.json"

# Hand-read from tests/fixtures/LoxAPP3.json and the actual HA core
# translation key layout (homeassistant/helpers/translation.py,
# async_translate_state: ``component.{platform}.entity.{domain}.
# {translation_key}.state.{state}``).
SWITCH_NAME = "Living Room Light Switch"
SWITCH_UUID = "63746c3a-0157-9766-ffff-e6720526f6f6000087"
TEMP_NAME = "Temperature Parlour"
TEMP_UUID = "63746c3a-0109-96d7-ffff-572617475726000009"
OVERRIDE_STATE_SLUG = "window_open"
OVERRIDE_STATE_EN = "Window Open"


async def _setup_entry(hass, mock_entry) -> None:
    mock_entry.add_to_hass(hass)
    ok = await hass.config_entries.async_setup(mock_entry.entry_id)
    await hass.async_block_till_done()
    assert ok, "entry setup failed"
    assert mock_entry.state is ConfigEntryState.LOADED


def _collect_registry_rows(hass, entry_id: str) -> list[dict]:
    """One row per loxone entity in the registry, stable order."""
    entity_registry = er.async_get(hass)
    device_registry = dr.async_get(hass)
    rows = []
    for entry in entity_registry.entities.values():
        if entry.config_entry_id != entry_id:
            continue
        device = device_registry.async_get(entry.device_id) if entry.device_id else None
        rows.append(
            {
                "domain": entry.domain,
                "entity_id": entry.entity_id,
                "unique_id": entry.unique_id,
                # the name the registry stored (None = "use the device name")
                "name": entry.name,
                "original_name": entry.original_name,
                "has_entity_name": getattr(entry, "has_entity_name", None),
                "disabled": bool(entry.disabled),
                # NOTE: entry.device_id is a random per-run uuid and must
                # not be snapshotted (the device *name*/model are stable).
                "device_name": device.name if device else None,
                "device_model": device.model if device else None,
            }
        )
    rows.sort(key=lambda row: (row["domain"], row["entity_id"]))
    return rows


# --------------------------------------------------------------------------- #
# Snapshot (compare against the committed, hand-reviewed file; regenerate
# with LOXONE_ENTITY_SNAPSHOT_OUT for the PR review diff).
# --------------------------------------------------------------------------- #
def _write_snapshot(path: str, rows: list[dict]) -> None:
    """Blocking snapshot write; only called from the regeneration path."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(json.dumps(rows, indent=2) + "\n")


async def test_entity_registry_snapshot(hass, mock_connection, mock_entry, enable_custom_integrations):
    await _setup_entry(hass, mock_entry)
    rows = _collect_registry_rows(hass, mock_entry.entry_id)
    assert rows, "no loxone entities were registered"

    out_path = os.environ.get("LOXONE_ENTITY_SNAPSHOT_OUT")
    if out_path:
        # ASYNC230/240: the blocking write lives in a plain (sync) helper.
        _write_snapshot(out_path, rows)
        pytest.skip(f"snapshot regenerated at {out_path}")

    expected = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
    missing = [row["entity_id"] for row in expected if row not in rows]
    extra = [row["entity_id"] for row in rows if row not in expected]
    assert not missing, f"entities missing from the runtime registry: {missing}"
    assert not extra, f"unexpected entities in the runtime registry: {extra}"


# --------------------------------------------------------------------------- #
# Acceptance: no "Device Device" duplicates in the snapshot
# --------------------------------------------------------------------------- #
def _is_device_device_duplicated(row: dict) -> bool:
    """True when the UI duplicates the device name for this entity.

    The frontend shows the device name as the device label *and* the
    entity's own name on the entity row.  For ``has_entity_name``
    entities an *empty* entity name means "use the device name" and renders
    exactly once — that is correct.  Duplicating happens when the entity
    row carries a name that either equals the device name (pre-WP-5.1
    primaries; any sub-entity whose short name repeats the parent) or
    starts with it (the old ``"<device> <suffix>"`` construction built
    from the full control name on a device already named after it).
    """
    device = row["device_name"]
    if device is None:
        return False
    if row["has_entity_name"]:
        own = row["name"]  # None = "use the device name" (fine)
    else:
        own = row["name"] if row["name"] is not None else row["original_name"]
    if own is None or own == device:
        # "own == device" is only a problem when has_entity_name is off
        # (the UI then shows device name AND entity name side by side); with
        # has_entity_name and an *explicitly stored* (user-set) name equal
        # to the device name the same duplication renders.
        return not bool(row["has_entity_name"]) or row["name"] is not None
    return own.startswith(device) or device.startswith(own)


async def test_no_duplicate_device_device_names(hass, mock_connection, mock_entry, enable_custom_integrations):
    """No "Device Device" duplicates in the snapshot.

    Pre-WP-5.1: every primary entity stored the control's full name as
    ``original_name`` and the device registry stored the very same name —
    the UI rendered "Living Room Light Switch Living Room Light Switch".
    With ``has_entity_name`` adopted the device name is the display name
    of primaries and sub-entities carry short names, so nothing may
    repeat its device name.
    """
    await _setup_entry(hass, mock_entry)
    rows = _collect_registry_rows(hass, mock_entry.entry_id)
    duplicated = [row["entity_id"] for row in rows if _is_device_device_duplicated(row)]
    assert not duplicated, f"entities duplicating their device name: {duplicated}"


# --------------------------------------------------------------------------- #
# Acceptance: has_entity_name on every entry
# --------------------------------------------------------------------------- #
async def test_all_entries_have_entity_name(hass, mock_connection, mock_entry, enable_custom_integrations):
    await _setup_entry(hass, mock_entry)
    rows = _collect_registry_rows(hass, mock_entry.entry_id)
    without = [row["entity_id"] for row in rows if row["has_entity_name"] is not True]
    assert rows, "no loxone entities were registered"
    assert not without, f"entries without has_entity_name: {without}"


# --------------------------------------------------------------------------- #
# Primary entities: empty name attribute, stable unique id
# --------------------------------------------------------------------------- #
def _switch_kwargs() -> dict:
    return dict(
        name=SWITCH_NAME,
        uuidAction=SWITCH_UUID,
        room="Parlour",
        cat="",
        states={"active": f"{SWITCH_UUID}-state"},
        config_entry=None,
    )


def test_primary_switch_adopts_has_entity_name():
    switch = LoxoneSwitch(**_switch_kwargs())
    assert switch.has_entity_name is True
    # The primary entity of a device contributes no name of its own: the
    # device name is the display name (no more "Device Device").
    assert switch._attr_name is None
    # the raw Loxone control name is still available for device identity
    assert switch._lox_name == SWITCH_NAME
    assert switch.unique_id == SWITCH_UUID
    # the device is still named after the control itself
    assert switch._attr_device_info["name"] == SWITCH_NAME


def test_primary_analog_sensor_adopts_has_entity_name():
    sensor = LoxoneSensor(
        name=TEMP_NAME,
        uuidAction=TEMP_UUID,
        room="Parlour",
        cat="",
        states={"active": "other-uuid"},
        details={"format": "%.1f °C"},
        config_entry=None,
    )
    assert sensor.has_entity_name is True
    assert sensor._attr_name is None
    assert sensor.unique_id == TEMP_UUID
    assert sensor._attr_device_info["name"] == TEMP_NAME


# --------------------------------------------------------------------------- #
# Sub-entities: short names without the parent prefix
# --------------------------------------------------------------------------- #
def test_room_controller_override_uses_short_name():
    override = LoxoneRoomControllerOverride(
        name="Bedroom Controller",
        uuidAction="irc-uuid-0001",
        room="Bedroom",
        cat="",
        states={"overrideEntries": "irc-override-entries-uuid"},
        config_entry=None,
    )
    assert override.has_entity_name is True
    assert override._attr_name == "Comfort Override"
    assert override._attr_name != "Bedroom Controller Comfort Override"


def test_light_presence_switch_uses_short_name():
    presence = LoxoneLightPresenceSwitch(
        name="Living Light Controller",
        uuidAction="lcv2-uuid-0001",
        room="Parlour",
        cat="",
        states={"presence": "lcv2-presence-uuid"},
        config_entry=None,
        async_add_devices=lambda *_: None,
    )
    assert presence.has_entity_name is True
    assert presence._attr_name == "Presence Detection"


def test_lcv2_dimmer_sub_light_uses_short_name():
    dimmer = LoxoneDimmer(
        name="LCV2 Dimmer",
        uuidAction="lcv2-dimmer-uuid",
        room="",
        cat="",
        states={"position": "pos", "min": "min", "max": "max", "step": "step"},
        lightcontroller_id="lcv2-uuid-0001",
        lightcontroller_name="Living Light Controller",
        config_entry=None,
        async_add_devices=lambda *_: None,
    )
    # the sub-light carries only its own name — the device is named after
    # the light controller, so prefixing it again would duplicate it.
    assert dimmer._attr_name == "LCV2 Dimmer"
    assert dimmer._attr_device_info["name"] == "Living Light Controller"


# --------------------------------------------------------------------------- #
# Enum sensor + presets: translation key layout
# --------------------------------------------------------------------------- #
def test_override_reason_sensor_has_translation_key():
    sensor = LoxoneRoomControllerOverrideSensor(
        name="Override Reason",
        uuid="irc-override-reason-uuid",
        device_info={"identifiers": {(DOMAIN, "irc-uuid")}, "name": "Bedroom Controller"},
        parent_uuid="irc-uuid",
    )
    assert sensor._attr_translation_key == "override_reason"


@pytest.mark.parametrize("language", ["en", "de", "cs"])
def test_override_reason_translations_match_ha_core_layout(language):
    """HA core resolves enum sensor states via
    ``component.{platform}.entity.{domain}.{translation_key}.state.{state}``
    (homeassistant/helpers/translation.py).  The shipped files must
    therefore nest under ``entity.sensor.<translation_key>`` — a nested
    ``entity.sensor.loxone.<translation_key>`` would never be found.
    """
    path = REPO_ROOT / "custom_components" / DOMAIN / "translations" / f"{language}.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    flat = recursive_flatten("component.loxone.entity.", data["entity"])

    key = f"component.loxone.entity.sensor.override_reason.state.{OVERRIDE_STATE_SLUG}"
    assert key in flat, f"{language}.json does not carry {key!r}"

    if language == "en":
        # hand-read from the shipped en translation (a literal, not a
        # computed value): this key must render in the UI.
        assert flat[key] == OVERRIDE_STATE_EN

    # the old, unreachable layout must be gone
    stale_key = f"component.loxone.entity.sensor.loxone.override_reason.state.{OVERRIDE_STATE_SLUG}"
    assert stale_key not in flat, f"{language}.json still carries the dead {stale_key!r} path"
